default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { nil } %>
  username: <%= ENV.fetch("POSTGRES_USER") { nil } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>
  pool: <%= ENV.fetch("POSTGRES_POOL_SIZE") { 5 } %>

development:
  <<: *default
  database: sample-spa_development

test:
  <<: *default
  database: sample-spa_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>